name = "Architectury API (Forge)"
filename = "architectury-1.30.54.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/976/architectury-1.30.54.jar"
hash-format = "sha1"
hash = "264deb4cc2a5afdec1a1f7b50459821fd5f2dd13"

[update]
[update.curseforge]
file-id = 3666976
project-id = 419699
