name = "Architectury API (Forge)"
filename = "architectury-1.30.55.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/614/architectury-1.30.55.jar"
hash-format = "sha1"
hash = "38e9b51f0b7af70c1fbca3b4134838c287b970af"

[update]
[update.curseforge]
file-id = 3671614
project-id = 419699
