name = "Architect's Palette"
filename = "Architects-Palette-1.16.4-1.1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3619/985/Architects-Palette-1.16.4-1.1.5.jar"
hash-format = "sha1"
hash = "67a665eda8b4e892b28fbd0890ccb565b5942ddf"

[update]
[update.curseforge]
file-id = 3619985
project-id = 433862
