name = "Better Mods Button [Forge]"
filename = "BetterModsButton-v1.0.5-1.16.5-Forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3519/38/BetterModsButton-v1.0.5-1.16.5-Forge.jar"
hash-format = "sha1"
hash = "0420d2e1633ee458d64e67035287fbcc081d57cd"

[update]
[update.curseforge]
file-id = 3519038
project-id = 541584
