name = "The Endergetic Expansion"
filename = "endergetic-1.16.4-3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3154/938/endergetic-1.16.4-3.0.0.jar"
hash-format = "sha1"
hash = "b9e2e605602cc161ddbd152775cd199098956889"

[update]
[update.curseforge]
file-id = 3154938
project-id = 291509
