name = "Farmer's Delight Compats"
filename = "farmersdelightintegrations-1.16.5-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3439/904/farmersdelightintegrations-1.16.5-1.2.jar"
hash-format = "sha1"
hash = "5e13f4cf8c69060c8aa34355c639cca8ef71ef7b"

[update]
[update.curseforge]
file-id = 3439904
project-id = 455519
