name = "InsaneLib"
filename = "InsaneLib-1.4.2-mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/474/InsaneLib-1.4.2-mc1.16.5.jar"
hash-format = "sha1"
hash = "435f082764f26495480d79700a1980b353efeaca"

[update]
[update.curseforge]
file-id = 3599474
project-id = 465109
