name = "Kiwi 🥝 (Forge)"
filename = "Kiwi-1.16.5-3.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3536/245/Kiwi-1.16.5-3.6.1.jar"
hash-format = "sha1"
hash = "b21d0e18f0552e28fc9175dcb4472094b8e4b688"

[update]
[update.curseforge]
file-id = 3536245
project-id = 303657
