name = "More Minecarts and Rails"
filename = "moreminecarts-1.3.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3650/530/moreminecarts-1.3.15.jar"
hash-format = "sha1"
hash = "d9ccd9f0a6b1f760155c252de0972b0cbe00eb20"

[update]
[update.curseforge]
file-id = 3650530
project-id = 440845
