name = "Music Maker Mod"
filename = "xercamusic-1.16.5-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3661/15/xercamusic-1.16.5-2.0.0.jar"
hash-format = "sha1"
hash = "96294fe03889ab1900ed82536b25a1102a84afde"

[update]
[update.curseforge]
file-id = 3661015
project-id = 341448
