name = "Not Enough Crashes (Forge)"
filename = "notenoughcrashes-4.1.4+1.16.5-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/847/notenoughcrashes-4.1.4+1.16.5-forge.jar"
hash-format = "sha1"
hash = "29320598177149b2236bd06269fe9b754f62a7a0"

[update]
[update.curseforge]
file-id = 3606847
project-id = 442354
