name = "Paragliders"
filename = "Paraglider-1.16.5-1.3.2.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3541/665/Paraglider-1.16.5-1.3.2.7.jar"
hash-format = "sha1"
hash = "80ecf25a55e660411651a942605fc23afb517296"

[update]
[update.curseforge]
file-id = 3541665
project-id = 289240
