name = "Passable Foliage 🌳"
filename = "PassableFoliage-1.16.5-2.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3480/488/PassableFoliage-1.16.5-2.4.0.jar"
hash-format = "sha1"
hash = "e8c1bcfbe61129c224e8debc815b140c2fd010a1"

[update]
[update.curseforge]
file-id = 3480488
project-id = 379887
