name = "Paxi (Forge)"
filename = "Paxi-Forge-1.16.4-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3426/545/Paxi-Forge-1.16.4-1.0.jar"
hash-format = "sha1"
hash = "098ffd13bb48fea58cd8c721bd9e61e0a57c2d38"

[update]
[update.curseforge]
file-id = 3426545
project-id = 515708
