name = "RoadRunner"
filename = "RoadRunner-mc1.16.5-1.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3683/120/RoadRunner-mc1.16.5-1.4.1.jar"
hash-format = "sha1"
hash = "b53b54eb9729e8081842e624359324a83a244a96"

[update]
[update.curseforge]
file-id = 3683120
project-id = 529754
