name = "RoadRunner"
filename = "RoadRunner-mc1.16.5-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3565/489/RoadRunner-mc1.16.5-1.4.0.jar"
hash-format = "sha1"
hash = "6e0424b82f0569a1b82902edd5c96b4341b3b8ac"

[update]
[update.curseforge]
file-id = 3565489
project-id = 529754
