name = "Skin Layers 3D (Fabric/Forge)"
filename = "3dSkinLayers-forge-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3456/514/3dSkinLayers-forge-1.1.0.jar"
hash-format = "sha1"
hash = "7f7e529371eade9915cf7f727545783127186072"

[update]
[update.curseforge]
file-id = 3456514
project-id = 521480
