name = "Smarter Farmers (farmers replant)"
filename = "smarterfarmers-1.16.5-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3482/654/smarterfarmers-1.16.5-1.2.1.jar"
hash-format = "sha1"
hash = "3c352b672e087098de72765666ad49b71dac6ffd"

[update]
[update.curseforge]
file-id = 3482654
project-id = 491290
