name = "Snow! Real Magic! ⛄ (Forge)"
filename = "SnowRealMagic-1.16.4-2.9.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3592/119/SnowRealMagic-1.16.4-2.9.0.jar"
hash-format = "sha1"
hash = "81e33348787e154506a63c9b93fa9e0410d29acd"

[update]
[update.curseforge]
file-id = 3592119
project-id = 308663
