name = "Spartan Weaponry"
filename = "SpartanWeaponry-1.16.4-2.1.0-beta-4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3291/850/SpartanWeaponry-1.16.4-2.1.0-beta-4.jar"
hash-format = "sha1"
hash = "0103fdff3b03e282090d4cbdfa44771636cf8ced"

[update]
[update.curseforge]
file-id = 3291850
project-id = 278141
