name = "Spiders 2.0"
filename = "spiders-2.0-1.16.4-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3103/152/spiders-2.0-1.16.4-1.0.4.jar"
hash-format = "sha1"
hash = "8aed00f33a26e0a7613a2fdd4603fc9be14b9ed1"

[update]
[update.curseforge]
file-id = 3103152
project-id = 410497
