name = "StepUp"
filename = "StepUp-1.16.4-0.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3179/485/StepUp-1.16.4-0.2.0.jar"
hash-format = "sha1"
hash = "7eddde9c2f007a4e90defb58cfdfffbe5a05b209"

[update]
[update.curseforge]
file-id = 3179485
project-id = 239236
