name = "Storage Drawers"
filename = "StorageDrawers-1.16.3-8.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3611/471/StorageDrawers-1.16.3-8.5.1.jar"
hash-format = "sha1"
hash = "4e8a3512a795833e047305d0b46bb3b74d45f73f"

[update]
[update.curseforge]
file-id = 3611471
project-id = 223852
