name = "Straw Golem Reborn - Forge"
filename = "strawgolem-1.16-1.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3057/272/strawgolem-1.16-1.9.jar"
hash-format = "sha1"
hash = "a4be39912298b3abfdaccc1d8c003f3544ebbfe1"

[update]
[update.curseforge]
file-id = 3057272
project-id = 387580
