name = "Upgrade Aquatic"
filename = "upgrade_aquatic-1.16.5-3.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3561/148/upgrade_aquatic-1.16.5-3.1.2.jar"
hash-format = "sha1"
hash = "9886b2fc6a3098d0128e7076011c9f73effc70a9"

[update]
[update.curseforge]
file-id = 3561148
project-id = 326895
