name = "Wall-Jump! [FORGE]"
filename = "walljump-forge-1.16.4-1.3.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3193/207/walljump-forge-1.16.4-1.3.7.jar"
hash-format = "sha1"
hash = "319a2b8ebcc7545ea5cb7e533470177c1cdf8c42"

[update]
[update.curseforge]
file-id = 3193207
project-id = 295319
