name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.4_Forge_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3686/603/XaerosWorldMap_1.20.4_Forge_1.16.5.jar"
hash-format = "sha1"
hash = "a8ad63ff77025cc1772e9c4ecf19cac08f2ab1ca"

[update]
[update.curseforge]
file-id = 3686603
project-id = 317780
