name = "Xaero's Minimap"
filename = "Xaeros_Minimap_22.3.1_Forge_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3686/589/Xaeros_Minimap_22.3.1_Forge_1.16.5.jar"
hash-format = "sha1"
hash = "fde45834a484fa6eaf960fc8f09023922c570004"

[update]
[update.curseforge]
file-id = 3686589
project-id = 263420
